local _, ns = ...

-- The default layout and settings: the author's own setup, exported from the
-- game. Applied over the base defaults in Core.lua, so options added later
-- keep their base default. "Reset positions" returns to this layout.
local LAYOUT = {
	["swing"] = {
		["enabled"] = true,
		["height"] = 15,
		["ranged"] = true,
		["offhand"] = true,
		["width"] = 352,
	},
	["bags"] = {
		["enabled"] = true,
		["columns"] = 11,
		["spacing"] = 3,
		["pos"] = {
			"RIGHT",
			"RIGHT",
			-273.0004577636719,
			-109.4996948242188,
		},
		["size"] = 42,
	},
	["minimap"] = {
		["enabled"] = true,
		["size"] = 236,
		["zoneText"] = true,
	},
	["alerts"] = {
		["repairPct"] = 20,
		["cdIdleAlpha"] = 0.5,
		["ammoLow"] = 200,
		["wWeapon"] = true,
		["wRepair"] = true,
		["wAmmo"] = true,
		["wGear"] = true,
		["warnings"] = true,
		["lowHealth"] = 30,
		["cdSize"] = 34,
		["enabled"] = true,
		["wFood"] = true,
		["wAttack"] = true,
		["combatText"] = true,
		["procs"] = true,
		["cooldowns"] = false,
		["buffs"] = true,
		["wPet"] = true,
		["lowHealthOn"] = true,
	},
	["party"] = {
		["enabled"] = true,
		["spacing"] = 6,
		["height"] = 40,
		["showPlayer"] = true,
		["width"] = 180,
	},
	["skins"] = {
		["enabled"] = true,
	},
	["raid"] = {
		["enabled"] = true,
		["spacing"] = 4,
		["height"] = 40,
		["rangeFade"] = true,
		["width"] = 84,
	},
	["positions"] = {
		["Bar3"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			-1,
			202,
		},
		["PlayerCast"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			0,
			295,
		},
		["TargetCast"] = {
			"BOTTOMRIGHT",
			"UIParent",
			"BOTTOMRIGHT",
			-338,
			289,
		},
		["Bar8"] = {
			"CENTER",
			"UIParent",
			"CENTER",
			0,
			-141,
		},
		["Focus"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			-357,
			248,
		},
		["Target"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			285,
			352,
		},
		["Raid"] = {
			"LEFT",
			"UIParent",
			"LEFT",
			58,
			192,
		},
		["PetBar"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			1,
			251,
		},
		["Bar2"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			1,
			104,
		},
		["Bar1"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			0,
			52,
		},
		["Pet"] = {
			"TOPLEFT",
			"UIParent",
			"TOPLEFT",
			275,
			-67,
		},
		["MicroMenu"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			28,
			0,
		},
		["Player"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			-284,
			352,
		},
		["TargetTarget"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			350,
			321,
		},
		["Cooldowns"] = {
			"RIGHT",
			"UIParent",
			"RIGHT",
			-429,
			177,
		},
		["StanceBar"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			-233,
			123,
		},
		["Swing"] = {
			"BOTTOM",
			"UIParent",
			"BOTTOM",
			0,
			188,
		},
		["TargetAuras"] = {
			"BOTTOMRIGHT",
			"UIParent",
			"BOTTOMRIGHT",
			-352,
			314,
		},
	},
	["profileName"] = "NovaUI",
	["xpbar"] = {
		["enabled"] = true,
		["showText"] = true,
		["reputation"] = true,
		["ticks"] = true,
		["height"] = 5,
	},
	["edit"] = {
		["snapGrid"] = true,
		["grid"] = 32,
		["snapFrames"] = true,
	},
	["globalFont"] = true,
	["tooltip"] = {
		["enabled"] = true,
		["cursor"] = false,
		["qualityBorder"] = true,
	},
	["castbars"] = {
		["enabled"] = true,
		["targetWidth"] = 230,
		["scale"] = 1,
		["playerWidth"] = 260,
		["latency"] = true,
		["target"] = true,
		["targetHeight"] = 18,
		["icon"] = true,
		["playerHeight"] = 22,
	},
	["actionbars"] = {
		["enabled"] = true,
		["hideArt"] = true,
		["emptySlots"] = true,
		["bars"] = {
			["bar3"] = {
				["enabled"] = false,
				["buttons"] = 7,
				["order"] = "row",
				["rows"] = 1,
				["mouseover"] = false,
				["cols"] = 7,
				["corner"] = "TOPLEFT",
				["spacing"] = 2,
				["perRow"] = 12,
				["vspacing"] = 5,
				["alpha"] = 0.8500000000000001,
				["size"] = 34,
			},
			["bar6"] = {
				["enabled"] = false,
				["buttons"] = 12,
				["order"] = "row",
				["rows"] = 12,
				["mouseover"] = false,
				["cols"] = 1,
				["corner"] = "TOPLEFT",
				["spacing"] = 4,
				["perRow"] = 1,
				["vspacing"] = 4,
				["alpha"] = 1,
				["size"] = 34,
			},
			["bar2"] = {
				["enabled"] = true,
				["buttons"] = 9,
				["order"] = "row",
				["rows"] = 2,
				["mouseover"] = false,
				["cols"] = 6,
				["corner"] = "TOPLEFT",
				["spacing"] = 5,
				["perRow"] = 12,
				["vspacing"] = 5,
				["alpha"] = 1,
				["size"] = 39,
			},
			["bar1"] = {
				["enabled"] = true,
				["buttons"] = 5,
				["order"] = "row",
				["rows"] = 1,
				["mouseover"] = false,
				["cols"] = 5,
				["corner"] = "TOPLEFT",
				["spacing"] = 6,
				["perRow"] = 12,
				["vspacing"] = 5,
				["alpha"] = 1,
				["size"] = 47,
			},
			["bar8"] = {
				["enabled"] = false,
				["buttons"] = 12,
				["order"] = "row",
				["rows"] = 1,
				["mouseover"] = false,
				["cols"] = 12,
				["corner"] = "TOPLEFT",
				["spacing"] = 4,
				["perRow"] = 12,
				["vspacing"] = 4,
				["alpha"] = 1,
				["size"] = 34,
			},
			["bar5"] = {
				["enabled"] = false,
				["buttons"] = 12,
				["order"] = "row",
				["rows"] = 12,
				["mouseover"] = false,
				["cols"] = 1,
				["corner"] = "TOPLEFT",
				["spacing"] = 4,
				["perRow"] = 1,
				["vspacing"] = 4,
				["alpha"] = 1,
				["size"] = 34,
			},
			["bar7"] = {
				["enabled"] = false,
				["buttons"] = 12,
				["order"] = "row",
				["rows"] = 12,
				["mouseover"] = false,
				["cols"] = 1,
				["corner"] = "TOPLEFT",
				["spacing"] = 4,
				["perRow"] = 1,
				["vspacing"] = 4,
				["alpha"] = 1,
				["size"] = 34,
			},
			["stance"] = {
				["enabled"] = true,
				["buttons"] = 6,
				["order"] = "row",
				["rows"] = 1,
				["mouseover"] = false,
				["cols"] = 6,
				["corner"] = "TOPLEFT",
				["spacing"] = 3,
				["perRow"] = 6,
				["vspacing"] = 3,
				["alpha"] = 1,
				["size"] = 28,
			},
			["pet"] = {
				["enabled"] = true,
				["buttons"] = 10,
				["order"] = "row",
				["rows"] = 1,
				["mouseover"] = false,
				["cols"] = 10,
				["corner"] = "TOPLEFT",
				["spacing"] = 3,
				["perRow"] = 10,
				["vspacing"] = 3,
				["alpha"] = 1,
				["size"] = 28,
			},
			["bar4"] = {
				["enabled"] = false,
				["buttons"] = 12,
				["order"] = "row",
				["rows"] = 12,
				["mouseover"] = false,
				["cols"] = 1,
				["corner"] = "TOPLEFT",
				["spacing"] = 4,
				["perRow"] = 1,
				["vspacing"] = 4,
				["alpha"] = 1,
				["size"] = 34,
			},
		},
		["hotkeys"] = true,
		["macroNames"] = false,
	},
	["language"] = "tr",
	["font"] = "Interface\\AddOns\\NovaUI\\Media\\Fonts\\Inter.ttf",
	["chat"] = {
		["enabled"] = false,
		["alpha"] = 0.55,
	},
	["micromenu"] = {
		["enabled"] = true,
		["hideBags"] = false,
		["clock24"] = true,
		["height"] = 30,
		["size"] = 14,
		["alpha"] = 1,
		["labels"] = true,
	},
	["nameplates"] = {
		["outline"] = true,
		["nameSize"] = 9,
		["castSize"] = 8,
		["textSize"] = 8,
		["percent"] = true,
		["enabled"] = true,
	},
	["auras"] = {
		["enabled"] = true,
		["skinPlayer"] = true,
		["targetPerRow"] = 8,
		["target"] = true,
		["onlyMine"] = true,
		["targetSize"] = 24,
	},
	["unitframes"] = {
		["enabled"] = true,
		["fadeAlpha"] = 1,
		["style"] = "portrait",
		["showPercent"] = true,
		["scale"] = 0.9,
		["fadeOutOfCombat"] = true,
		["classColor"] = true,
		["portraitIntro"] = true,
	},
	["accent"] = {
		0.31,
		0.76,
		0.97,
	},
}

-- Personal or bookkeeping fields that must not become defaults.
LAYOUT.profileName, LAYOUT.lastVersion, LAYOUT.unitframes.portraitIntro = nil, nil, nil
LAYOUT.micromenu.hideBags = nil

local function IsList(t) return t[1] ~= nil end

local function Overlay(dst, src)
	for k, v in pairs(src) do
		if type(v) == "table" and not IsList(v) and type(dst[k]) == "table" then
			Overlay(dst[k], v)
		else
			dst[k] = v
		end
	end
end

local positions = LAYOUT.positions
LAYOUT.positions = nil
Overlay(ns.defaults, LAYOUT)
for name, pos in pairs(positions) do ns.defaultPositions[name] = pos end
